### ISSUE TITLE
About learn_graph.py

### ISSUE THREAD

**Issue by melarrr** [kevin-xuan/FOGS#2]
when i run learn_graph.py to get PEMS04's learngraph
i got AttributeError: 'Namespace' object has no attribute 'thresh_T',maybe thresh_cos also need to solve.
What should i do ,thank u?

**Comment by kevin-xuan** [comment]
Hello, sorry for the late reply. Do you follow the steps in the readme file? We first run "graph_preparation.py" to generate time correlation graph, and the parameters in this file include "Thres_T". Then, after learning node embeddings through node2vec algorithm, "learn_graph.py" is used to learn the final graph. The parameter in this file is "Thres_cos". There is no Thres_T parameter.

**Comment by turmony** [comment]
### 在readme文件运行的最后一步出现了这个问题
Namespace(no_cuda=False, data='../data/processed/PEMS04/', sensors_distance='../data/PEMS04/PEMS04.csv', dtw_distance='../data/PEMS04/adj_PEMS04_001.csv', learn_graph='../data/PEMS04/learn_mx.pkl', column_wise=False, normalizer='std', batch_size=32, num_of_vertices=307, construct_type='connectivity', in_dim=1, hidden_dims=[[64, 64, 64], [64, 64, 64], [64, 64, 64]], first_layer_embedding_size=64, out_layer_dim=128, history=12, horizon=12, strides=4, temporal_emb=True, spatial_emb=True, use_mask=True, activation='GLU', seed=10, learning_rate=0.003, lr_decay=True, lr_decay_step='15,40,70,105,145', lr_decay_rate=0.3, epochs=200, print_every=50, save='./garage/PEMS04/', expid=1, max_grad_norm=5.0, patience=50, log_file='../data/PEMS04/log_PEMS04', trend_embedding=False, use_trend=True, direct=False)
Use undirected graph
Normalize the dataset by Standard Normalization
loading data...
The shape of localized adjacency matrix: torch.Size([1228, 1228])
trainX: torch.Size([11904, 12, 307, 1])		 trainY: torch.Size([11904, 12, 307, 1])
valX:   torch.Size([1728, 12, 307, 1])		valY:   torch.Size([1728, 12, 307, 1])
testX:   torch.Size([3424, 12, 307, 1])		testY:   torch.Size([3424, 12, 307, 1])
mean:   208.8982		std:   157.3047
data loaded!
Applying learning rate decay.
模型可训练参数: 2,365,596
GPU使用情况:9.472
Use trend
compiling model...
### Traceback (most recent call last):
  File "C:\tfp_pro\FOGS-main\STFGNN\train.py", line 280, in <module>
    main()
  File "C:\tfp_pro\FOGS-main\STFGNN\train.py", line 199, in main
    loss = engine.train(trainx, trainy, trainx_slot, trainy_slot)
  File "C:\tfp_pro\FOGS-main\STFGNN\engine.py", line 121, in train
    output = self.model(input)  # B, T, N  # 换成趋势后,output变成趋势;不换之前，output是归一化的流量值
  File "C:\conda_envs\pyg\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\tfp_pro\FOGS-main\STFGNN\model.py", line 373, in forward
    x = model(x, self.mask)
  File "C:\conda_envs\pyg\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\tfp_pro\FOGS-main\STFGNN\model.py", line 201, in forward
    x_left = torch.tanh(self.dilation_conv_1(x_temp))
  File "C:\conda_envs\pyg\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\conda_envs\pyg\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\conda_envs\pyg\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [32, 64, 307, 12]
